0.4.2
Kotlin/kandy pull request #148
Opened 2023-05-15 10:57 UTC by AndreiKingsley

2023-05-16 12:43 UTC, devcrocod requested changes

2023-05-16 12:43 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/DatasetHandler.kt
> -        // TODO
What's todo?

2023-05-16 12:43 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/validation.kt
> +    if (value !in range) {
requieres

2023-05-24 09:10 UTC, devcrocod requested changes
For a pie chart always need to specify constant values for x and y?

2023-05-24 09:10 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/geomWrap.kt
> +        is LetsPlotGeom -> when(this) {
What's LetsPlotGeom?
Why is function not called LetsPlotGeom but Geom?

2023-05-24 09:10 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/layerWrap.kt
>          globalMappings + mappings
In what case is `else` needed?

2023-05-24 09:10 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/scaleWrap.kt
> +                            org.jetbrains.letsPlot.intern.Scale(
qualified name

2023-05-24 10:03 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/layerWrap.kt
>          globalMappings + mappings
This flag is used if we do not inherit mappings. It is necessary if we change dataset - for example if we use stats, we don't have old columns, so the mappings are not valid.

2023-05-24 10:04 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/geomWrap.kt
> +        is LetsPlotGeom -> when(this) {
There is a `Geom` interface in IR. `LetsPlotGeom` is implementation of it in lets-plot

2023-05-24 13:44 UTC, merged