Make rendering of Plot github-view-compatible
Kotlin/kandy pull request #155
Opened 2023-05-25 12:12 UTC by ileasile

We add an image with plot which is immediately hidden by JS under it. Github view doesn't execute JS, that's why on Github we see this image instead of JS-rendered plot.

See example notebook here: https://gist.github.com/ileasile/ea7e65a1d35d5175712d7ef94fd5fd95

2023-05-25 15:52 UTC, belovrv commented
We should probably use svg instead of png for fallback.

2023-05-26 12:10 UTC, devcrocod requested changes

2023-05-26 12:10 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/util/containerUtil.kt
> +    val ours = this
Seems this can be improved in the following way:
```kotlin
    return (this + other).mapValues { (k, v) ->
        if (k in this && k in other)
            join(this[k]!!, other[k]!!)
        else
            v
    }
```

2023-05-26 12:10 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/util/containerUtil.kt
> +            a is JsonPrimitive && a.isString -> {
Does this imply the addition of other branches here? If not, maybe we could simply `do if (...) ... else a`?

2023-05-26 12:16 UTC, devcrocod requested changes

2023-05-26 12:16 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/jupyter/Integration.kt
> +            val realWidth = (img.width / scale).toInt()
Shouldn't we round up here?

2023-05-26 12:16 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/jupyter/Integration.kt
> +            val id = UUID.randomUUID().toString()
The UUID format looks like "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
It would be better to replace all "-" characters with underscores or get rid of them entirely. So we wouldn't get an error when using getElementById.

2023-05-26 20:19 UTC, ileasile commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/jupyter/Integration.kt
> +            val id = UUID.randomUUID().toString()
`getElementById` accepts string, so it shouldn't be a problem

2023-05-26 20:45 UTC, ileasile commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/util/containerUtil.kt
> +    val ours = this
I'll do but it seems it's suboptimal

2023-05-26 21:03 UTC, ileasile commented
I've made the code look better, thanks @devcrocod

2023-05-26 21:55 UTC, belovrv commented
I believe it would be beneficial to relocate the code responsible for concealing non-JavaScript output to the kernel integration library. This code does not possess any distinct logic for Kandy and can be highly advantageous for other libraries, such as DataFrame.

2023-05-27 00:26 UTC, ileasile commented
@belovrv There is only one line of JS, and it contains id that should be anyway defined by the library. I don't think that making it abstract would benefit kandy or other libraries that want to utilise this approach

2023-05-30 11:48 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/util/containerUtil.kt
> +    val ours = this
We don't have such large objects that this would affect the performance

2023-05-30 11:50 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/jupyter/Integration.kt
> +            val id = UUID.randomUUID().toString()
I know
I just had a mistake in a similar code, so I'm playing it safe

2023-05-30 11:55 UTC, AndreiKingsley approved these changes

2023-05-30 11:57 UTC, devcrocod approved these changes

2023-05-30 11:58 UTC, merged