New API and fixes for group data.
Kotlin/kandy pull request #218
Opened 2023-09-18 15:00 UTC by AndreiKingsley

2023-10-11 18:21 UTC, devcrocod requested changes

2023-10-11 18:21 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupByPlotContext.kt
> +    //override val _plotContext: PlotContext = this
remove

2023-10-11 18:21 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/DatasetHandler.kt
> +    //private val columnAsRefOnly: Boolean = false,
remove

2023-10-11 18:21 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/DatasetHandler.kt
> +        return if (column is DataColumn<*>/* && !columnAsRefOnly*/) {
remove

2023-10-11 18:21 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/addDataset.kt
> +    return datasetHandlers.indices.last
lastIndex?

2023-10-11 18:21 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/ir/data/GroupedData.kt
> +    //public val keys: List<String> = groupBy.keys.columnNames()
remove

2023-10-11 18:21 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/data.kt
> +    val dataFrame = dataFrame
For what? you are not overriding the dataframe

2023-10-11 18:21 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/data.kt
>          else -> TODO()
Exception

2023-10-11 18:21 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/data.kt
>          else -> TODO()
and is an else branch required here?

2023-10-11 21:46 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/data.kt
>          else -> TODO()
yes, for possible TableData implementations

2023-10-11 21:47 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/data.kt
> +    val dataFrame = dataFrame
What "for what"? GroupData properties was changed

2023-10-12 12:00 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/contexts.kt
> +    abstract override val _datasetIndex: Int
Why need override _datasetIndex here?

2023-10-12 12:02 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/data.kt
> +    val dataFrame = dataFrame
ye, but for this you don’t need to take the dataframe into a separate variable

2023-10-12 12:02 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/data.kt
>          else -> TODO()
okay, so need Exception for else

2023-10-13 11:07 UTC, devcrocod approved these changes

2023-10-13 11:07 UTC, merged