Release fixes
Kotlin/kandy pull request #231
Opened 2023-10-25 11:54 UTC by AndreiKingsley

2023-10-30 15:47 UTC, devcrocod requested changes
I have questions about plurals. You should call a layer plural if its typical use involves multiple objects, such as bars or points.
Also check that the renaming also affects the documentation: kdocs, readme, notebooks.

2023-10-30 15:47 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxplots.kt
> +public inline fun LayerCollectorContext.boxplots(block: BoxplotsContext.() -> Unit) {
Can't there be one boxplot?

2023-10-30 15:47 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxes.kt
> + * boxes {
Is this a recognizable boxplot name?

2023-10-30 15:47 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/contexts.kt
> +        if (layers.isEmpty()) {
use check, it's more compact without if

2023-10-30 17:53 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxes.kt
> + * boxes {
Boxplot is a statistical plot [wiki definition](https://en.wikipedia.org/wiki/Box_plot).
Box (with whiskers) is a geom: it can be used not only for a boxplot but also for example candlestick plot

2023-10-31 11:40 UTC, devcrocod approved these changes

2023-10-31 12:04 UTC, merged