Kdoc kandy-lets-plot
Kotlin/kandy pull request #242
Opened 2023-11-02 23:38 UTC by devcrocod

* update kotlin version
* update jupyter plugin version
* add kdoc for layer interfaces and contexts
* refactor kdoc for layers
* rewrite samples in kdoc layers
* add jupyter test for samples from kdoc 
* close #200 
* close #199

2023-11-06 16:36 UTC, AndreiKingsley requested changes

2023-11-09 13:46 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/CoordFlip.kt
> + * Flip the axes of the default coordinate system.
annotation `Experimental`
in doc, can use
> Note:

2023-11-09 13:47 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/Reversed.kt
> + * Indicates whether the axes in the layer should be reversed.
annotation `Experimental`
in doc, can use
> Note:

2023-11-09 13:49 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxes.kt
> + * The `boxes` layer visualizes the distribution of a dataset through its quartiles.
I use `replace` for change boxplot to boxes.
Specifically here, I think it’s worth using “boxes”, since that’s what our method is called. But in other places, it's really worth renaming it to boxplot

2023-11-09 13:59 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/CoordFlip.kt
> + * Flip the axes of the default coordinate system.
Let's note that is not is not recommended for use and will be replaced with new API.

2023-11-09 13:59 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/Reversed.kt
> + * Indicates whether the axes in the layer should be reversed.
Let's note that is not is not recommended for use and will be replaced with new API.

2023-11-09 13:59 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxes.kt
> + * The `boxes` layer visualizes the distribution of a dataset through its quartiles.
Ok

2023-11-09 14:00 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxes.kt
> + * The `boxes` layer visualizes the distribution of a dataset through its quartiles.
We can not that boxplot is most common boxes usage

2023-11-10 09:27 UTC, AndreiKingsley approved these changes

2023-11-10 09:28 UTC, merged