Improve github static svg
Kotlin/kandy pull request #252
Opened 2023-11-21 21:53 UTC by AndreiKingsley

SVG is scalable now, doesn't cropped on big plots/plot bunches

Example: https://gist.github.com/AndreiKingsley/86751cf0973d445d49873f38b3a80bd7

2023-11-22 12:13 UTC, devcrocod requested changes
This is the same thing I mentioned in another PR. Here, there's no need to put the statistical examples into a separate 'statistical' folder. The reason is simple - in the examples at https://kotlin.github.io/kandy/examples.html they are all on the same level, so the same structure should be maintained in other places as well

2023-11-22 12:13 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/util/rendering.kt
> +        (listOf(updateSvg(splitted.first(), id)) + splitted.drop(1)).joinToString("\n")
What does update svg mean here? What's the problem with `buildSvgImageFromRawSpecs`?

2023-11-27 09:47 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/util/rendering.kt
> +        (listOf(updateSvg(splitted.first(), id)) + splitted.drop(1)).joinToString("\n")
`buildSvgImageFromRawSpecs` is Lets-Plot method. It creates SVG of constant size, so it's cropped on big plots. `updateSvg` makes it scalable, as well as adds `id` attribute also needed for static outputs.

2023-11-28 10:21 UTC, devcrocod approved these changes

2023-11-29 09:36 UTC, merged