Docs gallery SVG migration
Kotlin/kandy pull request #254
Opened 2023-11-22 16:18 UTC by AndreiKingsley

2023-11-22 17:27 UTC, devcrocod requested changes
This changes don't work for these examples

<img width="644" alt="image" src="https://github.com/Kotlin/kandy/assets/19648120/fa8e335a-a250-4752-adc7-fb8a382acaeb">

2023-11-22 17:27 UTC, devcrocod commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/tiles.kt
> +        val cols = listOf(
Return the old version
There is `shuffled(random)`

2023-11-22 17:27 UTC, devcrocod commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/lines.kt
> +        /*     // SampleEnd
Fix this comment

2023-11-22 17:27 UTC, devcrocod commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/lines.kt
> +        plotGrid(listOf(linePlot, pathPlot)).saveSample()
korro task doesn't work correctly for this sample

2023-11-22 17:27 UTC, devcrocod commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/lines.kt
> +        plotGrid(listOf(linePlot, pathPlot)).saveSample()
The aspect ratio for the preview broke, revert to the old picture.
<img width="568" alt="image" src="https://github.com/Kotlin/kandy/assets/19648120/5526f57f-b837-4686-b7a8-fa645808ec3a">

2023-11-22 23:54 UTC, devcrocod requested changes
For floating point problems, try using float instead of double in all such places. I'll check it myself after that.
For the `line_settings` example, then use `String` instead of `LocalDate`. It is also necessary to make an issue, since floating point calculations give a significant error.

2023-11-22 23:54 UTC, devcrocod commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/tiles.kt
> +        val random = Random(42)
use kotlin.random.Random(42)

because in documentation including only code, without imports

2023-11-22 23:54 UTC, devcrocod commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/lines.kt
> +    fun line_and_path_comp() {
don't rename method
or fix qualified name in the relevant document
```
Cannot find PsiElement corresponding to 'line_and_path_comp_1'
Cannot find PsiElement corresponding to 'line_and_path_comp_2'
```

2023-11-22 23:54 UTC, devcrocod commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/SampleUtil.kt
> -    fun Plot.saveSample(scale: Number = 1.175) {
Chance did not choose this coefficient
It is with this that the layout of the image coincides with the code block. Look how it looks in the [documentation](https://kotlin.github.io/kandy/simple-line.html)

<img width="787" alt="Screenshot 2023-11-23 at 00 43 58" src="https://github.com/Kotlin/kandy/assets/19648120/d12984f8-4064-4676-84ff-0f5c58a25a93">

and how it works locally

<img width="787" alt="image" src="https://github.com/Kotlin/kandy/assets/19648120/1b7b23aa-bda8-4e59-a5d9-11577fe51fd5">

2023-11-23 07:42 UTC, AndreiKingsley commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/SampleUtil.kt
> -    fun Plot.saveSample(scale: Number = 1.175) {
Ok, but why we should match code borders? This is **actual** plot size, and I want to show plot with it. We can have plots with different size in example, so let's show them with actual size, not scaled.
<img width="1021" alt="image" src="https://github.com/Kotlin/kandy/assets/49092338/3924cce9-1d51-4cb7-bd52-68e7d564b61d">

2023-11-23 11:08 UTC, devcrocod commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/SampleUtil.kt
> -    fun Plot.saveSample(scale: Number = 1.175) {
> Ok, but why we should match code borders?
Because it looks much better

2023-11-23 11:16 UTC, devcrocod commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/SampleUtil.kt
> -    fun Plot.saveSample(scale: Number = 1.175) {
The scaling factor is not so large that the perception of size is critical.  but at the same time the layout itself looks much better.

2023-11-23 11:18 UTC, AndreiKingsley commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/SampleUtil.kt
> -    fun Plot.saveSample(scale: Number = 1.175) {
So, are we ignoring size parameter of plot here?

2023-11-23 11:29 UTC, devcrocod commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/SampleUtil.kt
> -    fun Plot.saveSample(scale: Number = 1.175) {
already doing this
and I don't see you fixing it

You can do this: when we change the size, we change it and apply the scale. 
In this case, you will need to check that everything will be correct in the preview; if not, then generate additional images for the preview

2023-11-23 11:33 UTC, AndreiKingsley commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/SampleUtil.kt
> -    fun Plot.saveSample(scale: Number = 1.175) {
Already did the last one here 
https://github.com/Kotlin/kandy/blob/95d60c457536885896742e358939d7396c8f1820/kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/SampleUtil.kt#L27
and here 
https://github.com/Kotlin/kandy/blob/95d60c457536885896742e358939d7396c8f1820/kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/SampleUtil.kt#L35

2023-11-23 11:34 UTC, AndreiKingsley commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/samples/SampleUtil.kt
> -    fun Plot.saveSample(scale: Number = 1.175) {
If `savePreview` is true, an additional image for preview is generated with fixed size (600, 400)

2023-11-24 13:13 UTC, devcrocod approved these changes

2023-11-24 13:13 UTC, merged