Updates for candlestick
Kotlin/kandy pull request #319
Opened 2024-01-17 09:59 UTC by AndreiKingsley

Update LP and LPK versions to latest and added new parameters needed for candlestick implementation
- fixes #156 
- fixes #299

2024-01-18 10:12 UTC, AndreiKingsley commented
TODO: add documentation to `whiskerWidth` and `enableSideTooltips`

2024-01-24 09:51 UTC, devcrocod requested changes

2024-01-24 09:51 UTC, devcrocod commented on gradle.properties
> +version=0.5.1-dev-cs
What's mean cs?

2024-01-24 09:51 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/context/aes/WithWhiskerWidth.kt
> + * Interface for managing the `fatten` aesthetic, which is particularly useful for controlling
fatten?

2024-01-24 09:51 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/context/aes/WithWhiskerWidth.kt
> + * Interface for managing the `fatten` aesthetic, which is particularly useful for controlling
rewrite kdoc

2024-01-24 09:51 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/layerTooltips.kt
> +    enable: Boolean = true,
what happens if enable = false and enableSideTooltips = true?

2024-01-24 09:51 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/feature/LayerTooltips.kt
> +    val enable: Boolean,
don't like this naming

2024-01-24 09:51 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/feature/LayerTooltips.kt
> +    val enable: Boolean,
what about `show`?

2024-01-24 09:54 UTC, AndreiKingsley commented on gradle.properties
> +version=0.5.1-dev-cs
Removed, it was for testing purpose.

2024-01-24 09:54 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/context/aes/WithWhiskerWidth.kt
> + * Interface for managing the `fatten` aesthetic, which is particularly useful for controlling
done

2024-01-24 09:58 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/feature/LayerTooltips.kt
> +    val enable: Boolean,
`show=false` means there are tooltips but they are not shown, but why?

2024-01-24 10:07 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/layerTooltips.kt
> +    enable: Boolean = true,
In theory, the main tooltips should stop working and the side tooltips should work, but right now it doesn't work in lets-plot

2024-01-24 10:24 UTC, devcrocod commented on gradle.properties
> +version=0.6.0
why not "dev"

2024-01-24 10:25 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/layerTooltips.kt
> +    enable: Boolean = true,
#321

2024-01-24 10:27 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/layerTooltips.kt
> +    enable: Boolean = true,
Why it's not obvious?

2024-01-26 13:06 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/context/aes/WithWhiskerWidth.kt
> + * Interface for managing the `whiskerWidth` aesthetic, which is responsible for the length of boxplor whiskers.
Suggest: Interface for managing the `whiskerWidth` aesthetic, responsible for the length of boxplot whiskers.

2024-01-26 13:06 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/context/aes/WithWhiskerWidth.kt
> +     * Sets the `whiskerWidth` aesthetic, determining the ratio of the length of box ends to the width of the box.
Suggest: Sets the `whiskerWidth` aesthetic, determining the ratio of the length of box ends to the box's width.
		     * This aesthetic specifically applies to boxes-based plots (boxplot, candlestick, etc.).

2024-01-26 13:08 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/feature/LayerTooltips.kt
> +    val enable: Boolean,
I suggest following Kotlin standards for Boolean variables [](https://stackoverflow.com/questions/43317026/kotlin-naming-convention-for-boolean-returning-methods)
For example, isHidden or isShown

2024-01-26 13:09 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/feature/LayerTooltips.kt
> +            enable: Boolean,
isEnabled

2024-01-26 13:11 UTC, zaleslaw requested changes
I suggest converting naming for Boolean variables, probably across the whole library.
I also could do this

2024-01-29 11:57 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/feature/LayerTooltips.kt
> +            enable: Boolean,
I agree with Aleksei, if this is a parameter in a function, then the standard naming is clear, for dsl it is negotiable

2024-02-05 12:12 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/feature/LayerTooltips.kt
> +            enable: Boolean,
Okay, I was not entirely correct. 
https://kotlinlang.org/docs/coding-conventions.html#properties
In Kotlin, `isSomething` is used for read-only properties, also because getters/setters are not generated for them, and in such a case, it adheres to the java naming convention, but we do not support java. Also, in this case, it is a parameter, not a property

2024-02-08 12:12 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/feature.kt
> +    // TODO: temporary solution, moves side tooltips to main
Probably, it will be great to make a ticket and refer on it in the manner
// TODO: https://github.com/Kotlin/kandy/issues/33333

2024-02-08 12:13 UTC, zaleslaw approved these changes
Hey @AndreiKingsley I left some minor comments to your PR, please answer them before merging

2024-02-09 12:01 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/feature.kt
> +    if (variables.isNotEmpty() || lines?.isNotEmpty() == true) {
mb use `?:`
because isNotEmpty is a boolean method

2024-02-09 12:18 UTC, AndreiKingsley commented on docs/topics/guides/Tooltips-Guide.md
> +        tooltips(isEnabled = false)
Just `enable`?

2024-02-09 12:29 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/feature.kt
> +    if (variables.isNotEmpty() || lines?.isNotEmpty() == true) {
What do you mean?
We should check that it's not null and it's not empty?
`lines?.isNotEmpty() ?: false` ?

2024-02-09 14:25 UTC, devcrocod commented on docs/topics/guides/Tooltips-Guide.md
> +        tooltips(isEnabled = false)
I'm not sure
just to let you know
in this case it could be either way

2024-02-09 14:28 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/feature.kt
> +    if (variables.isNotEmpty() || lines?.isNotEmpty() == true) {
It seemed to me that there is some more convenient way when we check something for the nullable type
Is there some method like: lines.isNotNullAndEmpty? Because it seemed to me that this design problem had already been solved in Kotlin

2024-02-13 10:24 UTC, devcrocod approved these changes

2024-02-13 13:02 UTC, AndreiKingsley commented
@devcrocod please check kdoc change in the last commit before merge

2024-02-13 13:57 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/layerTooltips.kt
> + * Hides tooltips. Applies to all kinds of tooltips: axis, side and general tooltips.
axis?

2024-02-13 14:20 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/tooltips/layerTooltips.kt
> + * Hides tooltips. Applies to all kinds of tooltips: axis, side and general tooltips.
Yes, tooltips on axis are basically "axis tooltips"

2024-02-14 09:32 UTC, merged