Add FAQ section
Kotlin/kandy pull request #320
Opened 2024-01-19 11:44 UTC by AndreiKingsley

2024-01-24 10:15 UTC, devcrocod requested changes
Need to rewrite all answers

2024-01-24 10:15 UTC, devcrocod commented on docs/topics/Welcome.topic
> +            <a href="FAQs.md" type="search"/>
"search" doesn't suit for FAQ section
mb use "community" or "support" icon

2024-01-24 10:15 UTC, devcrocod commented on docs/topics/FAQs.md
> +## Where can I ask a question about Kandy, leave feedback or request a feature?
This can be without a question, just as an introductory paragraph

2024-02-01 11:39 UTC, AndreiKingsley commented
@devcrocod please review FAQ doc again. If it's OK, I send it for proofreading.

2024-02-01 14:21 UTC, devcrocod commented
@AndreiKingsley 
I don't like the last question because it's quite narrow. And the answer turns out to be the same
Otherwise 👍

2024-02-08 16:58 UTC, devcrocod approved these changes

2024-02-09 10:17 UTC, zaleslaw commented on docs/topics/FAQ.md
> +We’re keen to receive any Kandy-related feedback, questions, feature requests, or suggestions you may have.
' instead of  ,

2024-02-09 10:17 UTC, zaleslaw commented on docs/topics/FAQ.md
> +[corresponding issue](https://github.com/Kotlin/kandy/issues/27) for updates and cast your vote there as well.
remove `as well`

2024-02-09 10:19 UTC, zaleslaw commented on docs/topics/FAQ.md
> +## Is there geo tools/geo visualization support?
`are ` instead of `is`

2024-02-09 10:19 UTC, zaleslaw commented on docs/topics/FAQ.md
> +It would also be appreciated if you could describe your case and current toolset.
Please describe your case and current toolset

2024-02-09 10:20 UTC, zaleslaw commented on docs/topics/FAQ.md
> +## Does Kandy support dynamic plotting / animations?
plotting/animations instead of plotting / animations

2024-02-09 10:20 UTC, zaleslaw commented on docs/topics/FAQ.md
> + * At the moment, the Lets-Plot version of Kandy doesn’t support any kind of animations
At the moment, the Lets-Plot version of Kandy doesn't support any animations

2024-02-09 10:21 UTC, zaleslaw commented on docs/topics/FAQ.md
> +## My use case involves creating several layers with multiple series of data, and I can’t figure out how to create a legend for them (for their colors, for example). Is it possible?
with multiple data series

2024-02-09 10:21 UTC, zaleslaw commented on docs/topics/FAQ.md
> +## My use case involves creating several layers with multiple series of data, and I can’t figure out how to create a legend for them (for their colors, for example). Is it possible?
My use case involves creating several layers with multiple data series, and I need help figuring out how to make a legend for them (for their colors, for example). Is it possible?

2024-02-09 10:22 UTC, zaleslaw commented on docs/topics/FAQ.md
> +so at the moment the only solution is to use a [series hack](https://kotlin.github.io/kandy/series-hack-guide.html)
so, at the moment,

2024-02-09 10:22 UTC, zaleslaw commented on docs/topics/FAQ.md
> + * At the moment, no. This is a limitation of the Lets-Plot engine,
There is?

2024-02-09 10:23 UTC, zaleslaw approved these changes
Structure and questions are cool, I've just added some simplifications in some cases

2024-02-09 12:32 UTC, AndreiKingsley commented on docs/topics/FAQ.md
> +We’re keen to receive any Kandy-related feedback, questions, feature requests, or suggestions you may have.
?

2024-02-09 12:32 UTC, AndreiKingsley commented on docs/topics/FAQ.md
> +## Is there geo tools/geo visualization support?
Why?

2024-02-09 12:34 UTC, AndreiKingsley commented on docs/topics/FAQ.md
> +It would also be appreciated if you could describe your case and current toolset.
Why?

2024-02-09 12:36 UTC, AndreiKingsley commented on docs/topics/FAQ.md
> +## My use case involves creating several layers with multiple series of data, and I can’t figure out how to create a legend for them (for their colors, for example). Is it possible?
1. Ok
2. Why?

2024-02-09 12:36 UTC, AndreiKingsley commented on docs/topics/FAQ.md
> + * At the moment, no. This is a limitation of the Lets-Plot engine,
Why?

2024-02-09 14:19 UTC, devcrocod commented on docs/topics/FAQ.md
> +## Does Kandy support dynamic plotting / animations?
It depends on how the chapter looks on the web

2024-02-09 14:21 UTC, devcrocod commented on docs/topics/FAQ.md
> +## My use case involves creating several layers with multiple series of data, and I can’t figure out how to create a legend for them (for their colors, for example). Is it possible?
I disagree
"Data Series" is a common name for many things like in pandas, in some tools from microsoft, google. So "data series" may cause confusion among some people

2024-02-12 10:21 UTC, merged