new export api
Kotlin/kandy pull request #324
Opened 2024-01-30 14:12 UTC by AndreiKingsley

@devcrocod should we add `.toPNG()` and `toJPG()` extensions?

2024-01-30 14:14 UTC, AndreiKingsley commented
Close  #293

2024-01-31 11:34 UTC, devcrocod commented
No
Create issues for those and set the label "Good first issue"

2024-01-31 11:41 UTC, AndreiKingsley commented
I mean do we need it at all?

2024-02-01 14:49 UTC, AndreiKingsley commented
> I thought we were talking about a shortcut for save("image.svg") ~ toSVG("image")
 
 Should we add it?

2024-02-05 10:06 UTC, devcrocod commented
I think it's not necessary for now, can also create an issue for this for external contributors.

2024-02-05 10:40 UTC, devcrocod requested changes
I didn't see any tests. I think it would be good to add them for `toHtml` and `toSvg`

2024-02-05 10:40 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/internal/jsVersion.kt
> +internal val LETS_PLOT_JS_VERSION = "4.1.0"
the property should be const

2024-02-05 10:40 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toHTML.kt
> +    get() = PlotHtmlHelper.scriptUrl(LETS_PLOT_JS_VERSION)
`PlotHtmlHelper.scriptUrl(LETS_PLOT_JS_VERSION)` also used in Integration
In that case, the `scriptUrl` can be reused there, but it needs to be moved to internal package

2024-02-05 10:40 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toBufferedImage.kt
> +        scale.toDouble(),dpi?.toDouble() ?: Double.NaN
seems not okay to use Double.NaN

2024-02-05 10:40 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toBufferedImage.kt
> + */
missing patameters kdoc

2024-02-05 10:40 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toHTML.kt
> + * @param iFrame Whether to wrap HTML in IFrame
Is that really so? Or does it return isolated html that can then be placed in an iframe?

2024-02-05 10:40 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toSVG.kt
> +public fun Plot.toSVG(): String = PlotSvgExport.buildSvgImageFromRawSpecs(toLetsPlot().toSpec())
If I want to change the size of the Plot?

2024-02-05 11:19 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toBufferedImage.kt
> +        scale.toDouble(),dpi?.toDouble() ?: Double.NaN
Why? it's Lets-Plot function;  In it, to have the behavior we expect when dpi is not specified (in our API it is `null`), we need to pass `NaN` (you can make sure of this by looking at the code of this function https://github.com/JetBrains/lets-plot/blob/ed99e74b299158737394725972a785fb48ee313f/plot-image-export/src/jvmMain/kotlin/org/jetbrains/letsPlot/core/plot/export/PlotImageExport.kt#L106)

2024-02-05 11:24 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toHTML.kt
> + * @param iFrame Whether to wrap HTML in IFrame
Yes.
Check the code original function:
https://github.com/JetBrains/lets-plot/blob/ed99e74b299158737394725972a785fb48ee313f/plot-stem/src/commonMain/kotlin/org/jetbrains/letsPlot/core/util/PlotHtmlExport.kt#L14

2024-02-05 11:24 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toSVG.kt
> +public fun Plot.toSVG(): String = PlotSvgExport.buildSvgImageFromRawSpecs(toLetsPlot().toSpec())
Then what?

2024-02-05 11:49 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toBufferedImage.kt
> +        scale.toDouble(),dpi?.toDouble() ?: Double.NaN
Because using `Double.NaN` is generally not very good, as it's a special case. In this instance, of course, the problem is that lets-plot uses it

2024-02-05 12:01 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toSVG.kt
> +public fun Plot.toSVG(): String = PlotSvgExport.buildSvgImageFromRawSpecs(toLetsPlot().toSpec())
I mean parameter `plotSize`

2024-02-05 12:08 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toSVG.kt
> +public fun Plot.toSVG(): String = PlotSvgExport.buildSvgImageFromRawSpecs(toLetsPlot().toSpec())
Then you should did it in the plot creation. Not sure if this parameter works at all.

2024-02-05 12:14 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toSVG.kt
> +public fun Plot.toSVG(): String = PlotSvgExport.buildSvgImageFromRawSpecs(toLetsPlot().toSpec())
And it's not used in Lets-Plot export API, not even internally.

2024-02-05 12:16 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toBufferedImage.kt
> + */
It's an internal function, should we have a full kdoc for it?

2024-02-05 13:07 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toSVG.kt
> +public fun Plot.toSVG(): String = PlotSvgExport.buildSvgImageFromRawSpecs(toLetsPlot().toSpec())
It's strange
okay

2024-02-06 11:26 UTC, devcrocod approved these changes

2024-02-06 11:26 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toBufferedImage.kt
> + */
Oh, so just copy from public fun, it's enough

2024-02-08 11:55 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toBufferedImage.kt
> + */
We also could use [MutableMap] and [BufferedImage] to refer to classes https://kotlinlang.org/docs/kotlin-doc.html#kdoc-syntax

2024-02-08 11:56 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/export/toBufferedImage.kt
> + * @return [BufferedImage] the created image representing the plot grid.
So, here [] are used!

2024-02-08 12:00 UTC, zaleslaw approved these changes

2024-02-12 10:20 UTC, merged