Style theme renaming
Kotlin/kandy pull request #326
Opened 2024-02-02 12:44 UTC by AndreiKingsley

fixes #127

2024-02-05 10:49 UTC, devcrocod requested changes
Also needed to regenerate samples in documentation and update notebooks

2024-02-05 10:49 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/Layout.kt
> +    var flavor: Theme? = null,
Then the property should also be renamed

2024-02-05 10:49 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/jupyter/JupyterConfig.kt
>  public class JupyterConfig : SelfInvocationContext {
Please remind me, why is this class public?

2024-02-05 11:28 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/jupyter/JupyterConfig.kt
>  public class JupyterConfig : SelfInvocationContext {
Because user can (and should) access public config property.

2024-02-05 11:31 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/jupyter/JupyterConfig.kt
>  public class JupyterConfig : SelfInvocationContext {
This class is responsible for setting up the display in Kotlin Notebook:
https://github.com/Kotlin/kandy/blob/fa8b0d7c77b5c61c9a9cd787c74d238dd2900b18/kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/jupyter/Integration.kt#L45

2024-02-06 11:27 UTC, devcrocod approved these changes

2024-02-08 12:01 UTC, zaleslaw commented on docs/topics/guides/Facets-Guide.md
> +        style(Style.Grey)
I am in doubts about this duplication style(Style..) or theme(Theme)

Could we solve this case without this word duplication for builders and constructors?

2024-02-08 12:03 UTC, zaleslaw commented on docs/topics/guides/Pie-Guide.md
> +    layout.style(blankTheme)
looks inconsistent with naming earlier (style(Style)... Probably, for consistency, it's better to rename to blankStyle?
If it's a bad naming for variable, probably, we don't need to rename theme->style at all?

2024-02-08 12:03 UTC, zaleslaw commented on docs/topics/guides/Plot-Bunch-Guide.md
> +val lowerTheme = style {
again, theme = style? What was the motivation behind this renaming?

2024-02-08 12:04 UTC, zaleslaw commented on docs/topics/guides/Quick-Start-Guide.md
> +fun plotWithTheme(style: Style? = null, title: String? = null): org.jetbrains.kotlinx.kandy.ir.Plot {
plotWithTheme(style: Style,,,) looks inconsistent

2024-02-08 12:06 UTC, zaleslaw commented on docs/topics/guides/Themes-Guide.md
> +        pointPlotWithTheme("Scatter plot", Style.None, themeOrangeConstructor),
better to rename to 

pointPlotWithStyle(Style.None, "Scatter plot", styleOrangeConstructor)

2024-02-08 12:07 UTC, zaleslaw commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/layout.kt
> +            theme = Theme.DARCULA,
Looks like a reason to rename Style :)

2024-02-08 12:08 UTC, zaleslaw requested changes
So, for me this renaming looks like a not fully finished PR

2024-02-09 14:44 UTC, devcrocod commented on docs/topics/guides/Styles-Guide.md
> +fun pointPlotWithStyle(
what happened with code style?

2024-02-09 14:47 UTC, AndreiKingsley commented on docs/topics/guides/Styles-Guide.md
> +fun pointPlotWithStyle(
What's wrong? Arguments are too large, pit them into separate lines.

2024-02-09 14:47 UTC, AndreiKingsley commented on docs/topics/guides/Styles-Guide.md
> +fun pointPlotWithStyle(
It's hard to read it in on line.

2024-02-13 14:55 UTC, AndreiKingsley commented
@zaleslaw now naming should be correct in all places

2024-02-16 13:38 UTC, zaleslaw commented
Sorry, @AndreiKingsley is it the same PR as #335 ?

2024-02-19 09:56 UTC, devcrocod approved these changes

2024-02-19 11:20 UTC, merged