Scale updates
Kotlin/kandy pull request #336
Opened 2024-02-21 17:06 UTC by AndreiKingsley

* close #311 
* close #301 
* close #306

2024-02-26 13:42 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +public sealed interface ScaleColorViridis<DomainType> {
Could you please provide KDocs for this interface and its parameters

2024-02-26 13:42 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/scaleWrap.kt
> +                    is ScaleColorViridis<*> -> when (aes) {
Sorry, but was this branch is covered with unit test?

2024-02-26 13:43 UTC, zaleslaw requested changes
Some moments are unclear for me and probably no updates for tests

2024-02-27 13:50 UTC, devcrocod requested changes

2024-02-27 13:50 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +public sealed interface ScaleColorViridis<DomainType> {
Why did you use sealed?

2024-02-27 13:50 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +    public val hueRange:  ClosedRange<Double>
I can't use Int?

2024-02-27 13:50 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +    override val transform: Transformation? = null
What could be the transformation for categorical?

2024-02-27 13:50 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +public sealed interface ScaleColorViridis<DomainType> {
Can this interface be inherited from CustomNonPositionalScale<DomainType, Color>?

2024-02-27 13:50 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/guide/model/AxisPosition.kt
> + * `BOTH` - set both (default and inverse) axis positions.
I don’t understand well, how is this can at the same time be: default and inverse?

2024-02-27 13:50 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/scaleWrap.kt
> +                    is ScaleColorViridis<*> -> when (aes) {
In a good way, such things should be put into separate functions so as not to create huge when's

2024-02-29 07:58 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/scaleWrap.kt
> +                    is ScaleColorViridis<*> -> when (aes) {
We don't have test for special scales yet, will add it later in other PR.

2024-02-29 08:00 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +public sealed interface ScaleColorViridis<DomainType> {
Why not? Why you might need to inherit it?

2024-02-29 08:03 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/scaleWrap.kt
> +                    is ScaleColorViridis<*> -> when (aes) {
We'll rewrite scale wrapper later

2024-02-29 13:07 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +    override val transform: Transformation? = null
It is added to the common interface for simplified wrapping to LetsPlot

2024-02-29 13:34 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +public sealed interface ScaleColorViridis<DomainType> {
if we split our code in the future

2024-02-29 13:35 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +    public val hueRange:  ClosedRange<Double>
No, i want write like 0..1, can I?

2024-02-29 13:37 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/guide/model/AxisPosition.kt
> + * `BOTH` - set both (default and inverse) axis positions.
still don't imagine this

2024-02-29 13:37 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/scaleWrap.kt
> +                    is ScaleColorViridis<*> -> when (aes) {
Yea, I get it
just reminded again

2024-02-29 13:38 UTC, devcrocod commented
There are still unresolved questions after the first review

2024-02-29 14:21 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +public sealed interface ScaleColorViridis<DomainType> {
Don't understand

2024-02-29 14:21 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +    public val hueRange:  ClosedRange<Double>
Yes, but why?

2024-02-29 14:22 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/guide/model/AxisPosition.kt
> + * `BOTH` - set both (default and inverse) axis positions.
<img width="609" alt="image" src="https://github.com/Kotlin/kandy/assets/49092338/65e792a1-3526-4e82-ad81-153c999f6daa">

2024-02-29 14:22 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/guide/model/AxisPosition.kt
> + * `BOTH` - set both (default and inverse) axis positions.
Wha's wrong?

2024-02-29 14:30 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +    override val transform: Transformation? = null
There're common problem from Lets-Plot I will fix them later with many others

2024-02-29 14:30 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +public sealed interface ScaleColorViridis<DomainType> {
Done

2024-02-29 14:45 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +    public val hueRange:  ClosedRange<Double>
Anyway what do you suggest? Make it `ClosedRange<T: Comparable<T> & Number>` ? I think it's too difficult for a such simple thing, and the type makes sense here.

2024-02-29 14:57 UTC, AndreiKingsley commented
@zaleslaw @devcrocod most of your remaining questions relate to a larger issue #126. There are a lot of things to change for this, let's do it lately.

2024-02-29 16:59 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +public sealed interface ScaleColorViridis<DomainType> {
What does sealed?

2024-02-29 17:00 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +    public val hueRange:  ClosedRange<Double>
Because it's api is better

2024-02-29 17:02 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +    override val transform: Transformation? = null
however, it is better to do it right away rather than leave it for later.  It just so happens that we have accumulated a lot of problems, there is no need to add another one

2024-02-29 17:06 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/guide/model/AxisPosition.kt
> + * `BOTH` - set both (default and inverse) axis positions.
ahh, now I understand. 
when we talked about inversed, I thought this meant that we inverted our axis, and it goes from right to left.  in this case, I’m not sure that inversed is appropriate (I’ve already made a mistake in understanding)

2024-02-29 17:15 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/guide/model/AxisPosition.kt
> + * `BOTH` - set both (default and inverse) axis positions.
Opposite?

2024-02-29 17:20 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +public sealed interface ScaleColorViridis<DomainType> {
Limits the possibility of inheritance? There're exactly 2 implementations. Why should we split it in the future?

2024-02-29 17:39 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +    override val transform: Transformation? = null
Done

2024-03-01 12:51 UTC, zaleslaw approved these changes

2024-03-01 14:11 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/colorVirdis.kt
> +    public val hueRange:  ClosedRange<Double>
Yeap, I agree that it makes no sense to support other types here. But I suggest we discuss our work with numeric types in the future

2024-03-01 14:21 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/guide/model/AxisPosition.kt
> + * `BOTH` - set both (default and inverse) axis positions.
Or can we separate these options for y and x axes? For example, for y-axe [`DEFAULT`, `RIGHT`, `BOTH`], for x-axis [`DEFAULT`, `TOP`, `BOTH`]?

2024-03-01 15:10 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/guide/model/AxisPosition.kt
> + * `BOTH` - set both (default and inverse) axis positions.
We can, but then we should split `Axis` class into 2 classes: `XAxis` and `YAxis`. Is it OK?

2024-03-04 10:00 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/guide/model/AxisPosition.kt
> + * `BOTH` - set both (default and inverse) axis positions.
upd: splitting is a bad solution, too much new code with mostly duplication

2024-03-04 10:05 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/guide/model/AxisPosition.kt
> + * `BOTH` - set both (default and inverse) axis positions.
Explanation for Both and inverse was not clear for me too.

2024-03-04 10:07 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/scales/guide/model/AxisPosition.kt
> + * `BOTH` - set both (default and inverse) axis positions.
Looks like options for x and y could be independent, we could imagine the situation, when we are customized something for x or y separately.

Or we should split them or support all the possible combinations of settings

2024-03-04 12:58 UTC, devcrocod approved these changes

2024-03-04 14:26 UTC, merged