Candlestick docs
Kotlin/kandy pull request #341
Opened 2024-02-22 15:21 UTC by AndreiKingsley

* close #278 
* close #149 

Before merge needs hotfix #337

2024-02-26 12:58 UTC, zaleslaw commented on docs/topics/guides/Candlestick-Guide.md
> +statCandlestickArgs :=
Pascal notation?

2024-02-26 12:59 UTC, zaleslaw commented on docs/topics/guides/Candlestick-Guide.md
> +Candlestick charts often use colors to visually indicate whether the value
Could you please add a paragraph to summarize what will be learned through this guide

2024-02-26 13:00 UTC, zaleslaw commented on docs/topics/samples/candlestick/Candlestick-Settings-2.md
> +Explore the 'Candlestick Settings 1' example using Kotlin and Kandy to understand the depth of
1 or 2? here Could we rename somehow for clarification?

2024-02-26 13:01 UTC, zaleslaw commented on docs/topics/samples/candlestick/Candlestick-Simple.md
> +Explore 'Candlestick Simple' in Kotlin using Kandy to understand the trend of a financial dataset.
Simple -> Basic(s)?

2024-02-26 13:04 UTC, zaleslaw requested changes
Really cool guides, examples and tests, I've enjoyed a lot of reading them.
I just only suggest some renaming and clarifications of names.

Probably, the intro for guides was to C2 level for me. Could it be downgraded to B2 level of English?:)

2024-02-27 13:31 UTC, devcrocod requested changes

2024-02-27 13:31 UTC, devcrocod commented on docs/images/guides/stat/guideCandlestickSimpleCandlestickPlot_dark.svg
Why are the images the same?
 - docs/images/guides/stat/guideCandlestickSimpleCandlestickPlotOnDf_dark.svg
 - docs/images/guides/stat/guideCandlestickSimpleCandlestickPlot_dark.svg

Have you saved more images than you need?

2024-02-27 13:31 UTC, devcrocod commented on docs/images/guides/stat/guideCandlestickSimpleCandlestickPlotOnDfWithSelectors.svg
Please check that you are reusing code and images where possible.

2024-02-27 13:31 UTC, devcrocod commented on docs/kd.tree
> +            <toc-element topic="Candlestick-Settings-1.md"/>
Please dont use numbers in topic titles

2024-02-27 13:31 UTC, devcrocod commented on docs/topics/guides/Candlestick-Guide.md
> +<card-summary>
Please shorten it, this is more than enough descriptions for the card

2024-02-27 13:31 UTC, devcrocod commented on docs/topics/guides/Candlestick-Guide.md
> +Explore Kandy's guide on creating candlesticks for insightful financial data analysis.
Here too, please shorten it, it will not be displayed good

2024-02-27 13:31 UTC, devcrocod commented on docs/topics/guides/Candlestick-Guide.md
> +closing, high, and low prices for a specific time period.
Highlight properties/aesthetics and keywords

2024-02-27 13:31 UTC, devcrocod commented on docs/topics/guides/Candlestick-Guide.md
> +    - `x` — candle `x`-position (often time or date describing);
If you use several points:
- put dots
- leave it open
- if you put a semicolon, then there should be a dot in the last sentence

2024-02-27 13:31 UTC, devcrocod commented on docs/topics/guides/Candlestick-Guide.md
> +### Generalized signature
`Common`

2024-02-27 13:31 UTC, devcrocod commented on docs/topics/samples/candlestick/Candlestick-Settings-1.md
> +</link-summary>
Very large card and link description

2024-02-29 06:56 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +statCandlestickArgs :=
Is it bad? It's a pseudocode describing arguments structure

2024-02-29 06:57 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +### Generalized signature
Generalized signature, i.e. arguments structure of statistic related functions

2024-02-29 06:58 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +### Generalized signature
"Common" doesn't quite fit IMO.

2024-02-29 07:10 UTC, AndreiKingsley commented on docs/images/guides/stat/guideCandlestickSimpleCandlestickPlot_dark.svg
These are 2 different tests corresponding to 2 different outputs

2024-02-29 07:13 UTC, AndreiKingsley commented
> Probably, the intro for guides was to C2 level for me. Could it be downgraded to B2 level of English?:)

@zaleslaw 
What exactly? No special vocabulary is used here, just standard Kotlin concepts as well as plotting terms described in [base guide](https://kotlin.github.io/kandy/quick-start-guide.html).

2024-02-29 07:17 UTC, AndreiKingsley commented on docs/images/guides/stat/guideCandlestickSimpleCandlestickPlotOnDfWithSelectors.svg
In some places images are nor reused on purpose - different code should produce identical images. If it's not, there's a mistake and we'll see it

2024-02-29 11:06 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +closing, high, and low prices for a specific time period.
But there are not properties/aesthetics

2024-02-29 11:45 UTC, AndreiKingsley commented on docs/topics/samples/candlestick/Candlestick-Simple.md
> +Explore 'Candlestick Simple' in Kotlin using Kandy to understand the trend of a financial dataset.
Let's discuss and rename for all then

2024-02-29 13:17 UTC, devcrocod commented on docs/topics/guides/Candlestick-Guide.md
> +statCandlestickArgs :=
I’m not sure what will be suitable for our documentation and our users

2024-02-29 13:20 UTC, devcrocod commented on docs/images/guides/stat/guideCandlestickSimpleCandlestickPlot_dark.svg
I understand it. Only the tests are identical, with the same data, only the API differs. Look at how the same tests were done with dataframes and collections. it is only saved there once.

2024-02-29 13:21 UTC, devcrocod commented on docs/images/guides/stat/guideCandlestickSimpleCandlestickPlotOnDfWithSelectors.svg
But it's not different code

2024-02-29 13:32 UTC, devcrocod requested changes
I also think that there is no need to overuse images. Because this complicates documentation support in the future.
In addition, the argument about testing is not valid, because we still have tests, and the saving functionality is already checked. And therefore there is no need to save images from each test, where the only difference is in different apis

Also you removed example from documentation

2024-02-29 13:32 UTC, devcrocod commented on docs/topics/Overview.md
>  <!---FUN quickstart_sample-->
?

2024-02-29 13:32 UTC, devcrocod commented on docs/topics/guides/Candlestick-Guide.md
> +closing, high, and low prices for a specific time period.
**_opening, closing, high, low_**

2024-02-29 13:46 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +statCandlestickArgs :=
What are you proposing?

2024-02-29 13:46 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +Candlestick charts often use colors to visually indicate whether the value
Done

2024-02-29 13:47 UTC, AndreiKingsley commented on docs/topics/samples/candlestick/Candlestick-Settings-2.md
> +Explore the 'Candlestick Settings 1' example using Kotlin and Kandy to understand the depth of
Done

2024-02-29 13:49 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +closing, high, and low prices for a specific time period.
It's not properties, more like common terms.

2024-02-29 13:50 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +### Generalized signature
Common = "everyone has the same one"

2024-02-29 13:50 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +### Generalized signature
But it can differ

2024-02-29 13:52 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +closing, high, and low prices for a specific time period.
It's a definition out of API context

2024-02-29 13:53 UTC, AndreiKingsley commented on docs/topics/Overview.md
>  <!---FUN quickstart_sample-->
Don't know why, just used korroClean + korro

2024-02-29 14:17 UTC, devcrocod commented on docs/topics/guides/Candlestick-Guide.md
> +closing, high, and low prices for a specific time period.
Therefore, they can be highlighted as bold or italic, not code. Things like this help navigate in text

2024-02-29 14:20 UTC, devcrocod commented on docs/topics/Overview.md
>  <!---FUN quickstart_sample-->
In this case, you check the files before committing. I suspect that korro had OOM and as a result, it broke down. Dokka consumes too much memory((

2024-02-29 14:23 UTC, devcrocod commented on docs/topics/guides/Candlestick-Guide.md
> +### Generalized signature
reasonable
so, if everything is clear to Aleksei, I think we can resolve this conversation

2024-02-29 14:26 UTC, devcrocod commented on docs/topics/guides/Candlestick-Guide.md
> +statCandlestickArgs :=
use a list, for example, or highlight it in some other way

2024-02-29 14:35 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +statCandlestickArgs :=
List? It doesn't make any sense. I think this pseudo-code for representing an abstract set of arguments is quite OK

2024-02-29 15:10 UTC, AndreiKingsley commented on docs/images/guides/stat/guideCandlestickSimpleCandlestickPlotOnDfWithSelectors.svg
Done

2024-02-29 15:14 UTC, AndreiKingsley commented on docs/images/guides/stat/guideCandlestickSimpleCandlestickPlot_dark.svg
Done

2024-02-29 15:14 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +closing, high, and low prices for a specific time period.
Done

2024-03-01 12:40 UTC, zaleslaw commented on docs/topics/guides/Candlestick-Guide.md
> +statCandlestickArgs :=
@AndreiKingsley let's just think about me like about external user, I was familiar with pseudocode algorithms years ago according to the CS education, but probably this is not what I'm waiting to parse with my eyes.

It could be rewritten in Kotlin style or with words as a text

2024-03-01 12:43 UTC, zaleslaw approved these changes

2024-03-01 13:04 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +statCandlestickArgs :=
Just `:` works ?

2024-03-01 13:09 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +statCandlestickArgs :=
No, type declaration `:` collision. 
Here we just need to emphasize that this is a purely **symbolic way** of passing the structure of the argument set. **Not a `List`**, but arguments separated by commas

2024-03-01 13:12 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +statCandlestickArgs :=
`:=` is a common symbol in mathematics that does not conflict with Kotlin

2024-03-01 13:13 UTC, AndreiKingsley commented on docs/topics/guides/Candlestick-Guide.md
> +statCandlestickArgs :=
`<-` ?

2024-03-01 15:08 UTC, merged