Add stat api reference
Kotlin/kandy pull request #353
Opened 2024-03-15 15:09 UTC by AndreiKingsley

part of #316

2024-03-19 10:22 UTC, zaleslaw approved these changes
@AndreiKingsley it's very difficult to review these changes because of tons of HTML changes, but I did not find something wrong reading the texts

2024-03-20 12:27 UTC, devcrocod requested changes
I don't like that you took out the signatures.
What should be taken out is what is reused, and these things are unique for each layer. Thus, you have made it difficult to maintain documentation for these layers.

2024-03-20 12:27 UTC, devcrocod commented on docs/topics/apiRef/Area-API.md
> +<include from = "interfaces.topic" element-id="interface-of-area"></include>
Why did you do this?

2024-03-20 12:32 UTC, AndreiKingsley commented on docs/topics/apiRef/Area-API.md
> +<include from = "interfaces.topic" element-id="interface-of-area"></include>
I reused it in https://github.com/Kotlin/kandy/blob/4016c1f876b2de229e2cbe553564a18a83f03137/docs/topics/apiRef/DensityPlot-API.md

2024-03-20 12:33 UTC, AndreiKingsley commented on docs/topics/apiRef/Area-API.md
> +### x {id="x_area"}
In statistic layers you have both `x` as argument and `x` as property. Sometimes in the topic there're several layers are described (see [boxplot](https://github.com/Kotlin/kandy/blob/4016c1f876b2de229e2cbe553564a18a83f03137/docs/topics/apiRef/Boxplot-API.md)).

2024-03-20 12:43 UTC, devcrocod commented on docs/topics/apiRef/Area-API.md
> +### x {id="x_area"}
it's area

2024-03-20 12:44 UTC, devcrocod commented on docs/topics/apiRef/Area-API.md
> +<include from = "interfaces.topic" element-id="interface-of-area"></include>
How? The naming doesn't match there?

2024-03-20 12:46 UTC, AndreiKingsley commented on docs/topics/apiRef/Area-API.md
> +<include from = "interfaces.topic" element-id="interface-of-area"></include>
What do you mean? There's include:
https://github.com/Kotlin/kandy/blob/4016c1f876b2de229e2cbe553564a18a83f03137/docs/topics/apiRef/DensityPlot-API.md?plain=1#L17

2024-03-20 12:49 UTC, AndreiKingsley commented on docs/topics/apiRef/Area-API.md
> +### x {id="x_area"}
yes, but in interfaces we should separate aesthetics references. (like in densityPlot there's `# x` argument and `# x` area aes)

2024-03-20 13:04 UTC, devcrocod commented
I’ll render it locally and see in more detail what it looks like

@zaleslaw It’s better to watch this kind of PR in idea with the writerside plugin, then you can watch the preview. Otherwise, it’s really difficult to review xml manually

2024-03-20 15:33 UTC, devcrocod approved these changes

2024-03-21 10:03 UTC, merged