Refactor an internal API system (part 1: new class system & remove all internal properties from DSL)
Kotlin/kandy pull request #376
Opened 2024-04-25 13:59 UTC by AndreiKingsley

This is the first part of several PRs with internal API redesigns. In this one, I reworked the class system used to build DSLs. The PR is big, but the minimum possible because it changes the root of the system.
What went into this PR
* A new system of DSL interfaces and classes, most classes/properties are now internal
* Implementations of these classes for Lets-Plot 
You can build api and lets-plot modules (and test them in a Kotlin Notebook, for example).
What is NOT included in this PR:
* `DatasetHandler` is still unchanged
* echarts module (only some rename was done)
* Tests 
  * I partially changed the tests in the api module to make them consistent with the new API, but a few did not make it yet - I commented them out; the tests in the api module are fully buildable and there're passed 
  * In lets-plot the tests are not consistent
     * Statistics needs to be updated as well

2024-05-27 12:29 UTC, AndreiKingsley commented on settings.gradle.kts
> -include("kandy-echarts")
Of course, but in other PR

2024-05-27 12:30 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/accessors.kt
> +internal val LayerBuilder.layerFeatures: MutableMap<FeatureName, LayerFeature>
Ok, but it's internal anyway.

2024-05-27 12:44 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/accessors.kt
> +internal val LayerBuilder.datasetHandler: DatasetHandler
1) When we want to add features, we do it as builder extension. We can't make all receivers for these extensions abstract classes, so most of them are interfaces.
2) Very often (almost always) we need details of the internal implementation (`datasetHandler`, `bindingHandler`), and we don't want to have any public accessors to them in builder interfaces.

So, yeah. I think it's a general problem of Kotlin DSLs.

2024-05-27 12:49 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupByPlotBuilder.kt
> +        ) as ColumnGroup<T>
Yes, AFAIU

2024-05-27 12:52 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/concatFixed.kt
> +// TODO should be fixed in dataframe: https://github.com/Kotlin/dataframe/issues/673
#390

2024-05-27 12:52 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/CustomPlotBuilder.kt
> +    internal val bindingCollector
No, why?

2024-05-27 13:03 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupByScope.kt
> +    override val datasetIndex: Int = plotBuilder.addDataset(
When initializing this scope, we add a new dataset, and take a new `datasetIndex`. If to be logically consistent, this logic should be performed before the constructor (done by the parent) and pass the `datasetIndex`, but I decided to put it in the constructor to simplify the code and perform this action in the constructor itself so there. This happens in several places (in stats for example, when we create a `statBin{}` scope), and it is easier to write `Scope(dataset)` than `Scope(dataset, plotBuilder.addDataset(dataset))` and you can make a mistake.

2024-05-27 13:03 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupedDataScope.kt
> +// must be LayerCreatorScope, marker of containing grouped data
Because it must be interface as well, but `LayerCreatorScope` is a class.

2024-05-27 13:07 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/LayerBuilderImpl.kt
> +    private var firstMapping: Boolean = true
Why? Is it a problem? However, in the third PR I moved it to `bindingHandler`.

2024-05-28 09:17 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/accessors.kt
> +internal val LayerBuilder.datasetHandler: DatasetHandler
These properties are internal. That means they don't need in other modules? Like example, in statistics

2024-05-28 09:21 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/LayerBuilderImpl.kt
> +    private var firstMapping: Boolean = true
yeap, this will be a problem when working with concurrent code

2024-05-28 13:15 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/LayerBuilderImpl.kt
> +    private var firstMapping: Boolean = true
1) Layer builder is not supposed to be used with concurrency (since there's no point in building layer non-sequential).
2) Answer for your question - no we can't.

2024-05-29 07:55 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/DataFramePlotBuilder.kt
> +// TODO(waiting for Context Parameters release https://github.com/Kotlin/KEEP/issues/367)
Moved to #391

2024-05-29 07:55 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/BindingHandler.kt
> +    abstract val datasetHandler: DatasetHandler
fixed

2024-05-29 09:46 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/CustomPlotBuilder.kt
> +    internal val bindingCollector
explicit Type, just intresting

2024-05-29 09:48 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupedDataScope.kt
> +// must be LayerCreatorScope, marker of containing grouped data
Okay, then I don't understand this comment

2024-05-29 09:49 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/LayerBuilderImpl.kt
> +    private var firstMapping: Boolean = true
I suppose it will be a problem with compose
Think we need to discuss it more deeply

2024-05-29 09:50 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/LayerBuilderImpl.kt
> +    private var firstMapping: Boolean = true
2. It can be as AtomicBoolean

2024-05-29 09:50 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/LayerBuilderImpl.kt
> +    private var firstMapping: Boolean = true
ps: then need concurrency collections at all

2024-05-29 09:52 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupedDataScope.kt
> +// must be LayerCreatorScope, marker of containing grouped data
All `GroupedDataScope` implementations must also be a  `LayerCreatorScope`.

2024-05-29 09:54 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/LayerBuilderImpl.kt
> +    private var firstMapping: Boolean = true
Let's discuss about concurrency in kandy later and in more depth.

2024-05-29 09:55 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupedDataScope.kt
> +// must be LayerCreatorScope, marker of containing grouped data
Internal rule since we can't make `LayerCreatorScope ` an interface / `GroupedDataScope` a class.

2024-05-29 10:17 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupedDataScope.kt
> +    public val key: ColumnGroup<T>
Still don't like using the key( This is not obvious to many, including me

2024-05-29 10:17 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupedDataScope.kt
> +// must be LayerCreatorScope, marker of containing grouped data
Okay, get it
In this case, then I don’t see any problems. Heirs inherit GroupedDataScope and LayerCreatorScope and It's okay

2024-05-29 10:17 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/SingleLayerPlotBuilder.kt
This class and MultilayerPlotBuilder raised questions for me. Why `SingleLayerPlotBuider` is inherited from `PlotBuilder`?

2024-05-29 10:29 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/CoordFlip.kt
> +public fun PlotBuilder.coordFlip() {
how many plot features do we have?

2024-05-29 10:29 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/builders/aes/ConstantSetter.kt
> +@Suppress("INVISIBLE_REFERENCE")
Why double Suppress?

2024-05-29 10:29 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/builders/aes/WithIntercept.kt
> +        get() = org.jetbrains.kotlinx.kandy.letsplot.layers.builders.aes.ConstantSetter(
import?

2024-05-29 10:29 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/builders/aes/WithLower.kt
> +        get() = org.jetbrains.kotlinx.kandy.letsplot.layers.builders.aes.ConstantSetter(
Import

2024-05-29 10:29 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/builders/aes/WithMiddle.kt
> +        get() = org.jetbrains.kotlinx.kandy.letsplot.layers.builders.aes.ConstantSetter(
Import

2024-05-29 10:29 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/builders/aes/WithSize.kt
> +@Suppress("INVISIBLE_MEMBER")
if you already mark bindingHandler in WithAes.kt, I suppose these suppress don't need

2024-05-29 10:32 UTC, devcrocod reviewed
It is necessary to write KDoc and check the current ones. Also, in abstract classes, you can use protected instead of internal, so that properties will be accessible in subclasses.

2024-05-29 10:33 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/CustomPlotBuilder.kt
Wrote in comments - for statistical plots

2024-05-29 10:37 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/CoordFlip.kt
> +public fun PlotBuilder.coordFlip() {
potentially as many as we want (as lets-plot has)

2024-05-29 10:39 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/SingleLayerPlotBuilder.kt
PlotBuilder has plot features regardless of whether the builder is a multi-layer, single-layer or any other type (for example build with series or any new way). For example - layout.

2024-05-29 10:50 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupedDataScope.kt
> +    public val key: ColumnGroup<T>
It's not an obligation, but a convenience. Sometimes it's important to perform mapping from a key, so if you write a `key.column`, you won't make a mistake.

2024-05-29 10:51 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupedDataScope.kt
> +    public val key: ColumnGroup<T>
You can still write the same thing without the key.

2024-05-29 11:00 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/builders/aes/WithSize.kt
> +@Suppress("INVISIBLE_MEMBER")
it's needed for internal aes constant values (`SIZE` etc)

2024-05-29 11:04 UTC, AndreiKingsley commented
In most cases, the properties need to be accessible outside of the class so they are made internal (i.e. actually public, but for modules, not to the user - what I called semi-internal)

2024-05-29 11:13 UTC, AndreiKingsley commented
@devcrocod add `ColumnsContainer` to `GroupedDataScope` with last commit, check please

2024-06-04 11:17 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupedDataScope.kt
> +    public val key: ColumnGroup<T>
In this case I get an exception of different column sizes

2024-06-04 11:19 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/CoordFlip.kt
> +public fun PlotBuilder.coordFlip() {
It seems to me that all our features are mainly layer features, and we only have experimental features for plot

2024-06-04 15:33 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/GroupedDataScope.kt
> +    public val key: ColumnGroup<T>
Where?

2024-06-04 15:34 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/CoordFlip.kt
> +public fun PlotBuilder.coordFlip() {
Layout?

2024-06-04 16:08 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/CoordFlip.kt
> +public fun PlotBuilder.coordFlip() {
And what's problem with plot features?

2024-06-05 11:09 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/CoordFlip.kt
> +public fun PlotBuilder.coordFlip() {
Not a problem, just a fact: the map of features is there, but the features are not

2024-06-05 12:03 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/Layout.kt
> +import org.jetbrains.kotlinx.kandy.dsl.internal.*
But then there would be a red highlighting

2024-06-05 12:10 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/Layout.kt
> +import org.jetbrains.kotlinx.kandy.dsl.internal.*
<img width="473" alt="image" src="https://github.com/Kotlin/kandy/assets/49092338/26f15103-3476-42b3-819f-f0f93c33f690">

2024-06-05 12:13 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/Layout.kt
> +import org.jetbrains.kotlinx.kandy.dsl.internal.*
And I don't want to do auto-optimisation for the same reason

2024-06-05 12:54 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/Layout.kt
> +import org.jetbrains.kotlinx.kandy.dsl.internal.*
Hm, I tried this before and it didn't work for me back then, but now it does.
Well, then we need to add this suppressing to almost every file.

2024-06-10 11:21 UTC, zaleslaw requested changes

2024-06-10 11:40 UTC, AndreiKingsley commented on settings.gradle.kts
> +//include("examples:idea-examples:echarts-simple")
Will be fixed in the 4th PR.

2024-06-10 11:44 UTC, AndreiKingsley commented on kandy-echarts/src/main/kotlin/org/jetbrains/kotlinx/kandy/echarts/layers/layers.kt
> + * - [ x][BarHandler.x] - mapping data on the x-axis.
KDocs works incorrect here without space for some reason.

2024-06-10 11:46 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/BindingHandler.kt
> +        values: List<DomainType>,
Why? You provide values of `DomainType` here, not types.

2024-06-10 11:48 UTC, AndreiKingsley commented on kandy-echarts/src/main/kotlin/org/jetbrains/kotlinx/kandy/echarts/layers/layers.kt
> + * - [ x][BarHandler.x] - mapping data on the x-axis.
And also this PR is not about echarts documentation at all, let's discuss it in future.

2024-06-10 11:49 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/BindingHandler.kt
> +     * @param value the value of the setting.
Well, it's "value." What alternative do you suggest? `settingValue`?

2024-06-10 11:50 UTC, AndreiKingsley commented on kandy-api/src/test/kotlin/org/jetbrains/kotlinx/kandy/builders/layerCollectorContext.kt
> +    fun `test addLayer`() {
All tests are fixed in the next PR.

2024-06-10 11:57 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/CustomPlotBuilder.kt
> +     * Plot builder dataset handler.
Ok, but still prefer "expanded" ones.

2024-06-18 10:25 UTC, devcrocod approved these changes

2024-06-18 11:37 UTC, zaleslaw approved these changes

2024-06-19 09:33 UTC, merged