Dataset handler rework
Kotlin/kandy pull request #392
Opened 2024-06-04 09:17 UTC by AndreiKingsley

`DatasetBuilder` (previously `DatasetHandler`) rework and also in addition to this (as these things are closely related), DataFrame implementations in the api module were separated.

2024-06-04 09:18 UTC, AndreiKingsley commented
`DynamicDataFrameBuilder` is not used yet due to the problem: https://github.com/Kotlin/dataframe/issues/715

2024-06-24 10:50 UTC, devcrocod requested changes

2024-06-24 10:50 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +            else -> TODO()
I think need to add Exception or other types

2024-06-24 10:50 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +                addColumn(column.rename(column.name() + "*"))
Dataframe has rename function, can we use it?

2024-06-24 10:50 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +        val columnId = addColumn(DataColumn.createValueColumn(name, values, Infer.Type))
If all values are null?

2024-06-24 10:50 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +        return addColumn(DataColumn.createValueColumn(name, values, Infer.Type))
Why do we create value column twice?

2024-06-24 10:50 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +            return NamedDataBuilder(dataFrame, initialBuilder)
It seems to me that it is better to use the kotlin style - create top level functions or extension functions. Java style with companion object is not the best option.

2024-06-24 10:50 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/GroupedDataBuilder.kt
> +        keys.forEach { key -> takeColumn(key) }
Get rid of init by putting this code in apply

2024-06-24 10:50 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/GroupedDataBuilder.kt
> +            buffer, keys
formatting

2024-06-24 10:50 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/NamedDataBuilder.kt
> +    constructor(df: DataFrame<*>, initialBuilder: DatasetBuilderImpl? = null): this(NamedData(df), initialBuilder)
formatting
Constructors are better placed above functions

2024-06-24 10:53 UTC, AndreiKingsley commented on gradle.properties
> +version=0.7.0-30-db
Sorry, it was only for local testing

2024-06-24 10:57 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/accessors.kt
> +        is MultiLayerPlotBuilder -> datasetBuilder
Does it? Everything looks fine:
<img width="930" alt="image" src="https://github.com/Kotlin/kandy/assets/49092338/c570dc95-95f3-4365-be85-a628d0ce4a5e">

2024-06-24 10:59 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/accessors.kt
> +internal val GroupedDataScope<*, *>.datasetBuilder: DatasetBuilderImpl
What do you expect instead of when branches? `this as LayerCreatorScope`? 
And we expect `DatasetBuilderImpl` since it's a dataframe implementation.

2024-06-24 11:00 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +            else -> TODO()
That's interesting, I don't know why `ColumnReference` is not sealed in dataframe.

2024-06-24 11:03 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +        val columnId = addColumn(DataColumn.createValueColumn(name, values, Infer.Type))
Could it be a problem?

2024-06-24 11:07 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +            return NamedDataBuilder(dataFrame, initialBuilder)
Storing factory methods in companion looks quite idiomatic to me

2024-06-24 16:04 UTC, zaleslaw commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +            return NamedDataBuilder(dataFrame, initialBuilder)
let's compare three signatures and code calls

```
class NamedDataBuilder {
    companion object {
        fun fromData(dataFrame: DataFrame<*>, initialBuilder: DatasetBuilderImpl? = null): NamedDataBuilder {
            return NamedDataBuilder(dataFrame, initialBuilder)
        }
    }
}
```

```
fun DataFrame<*>.fromData(initialBuilder: DatasetBuilderImpl? = null): NamedDataBuilder {
    return NamedDataBuilder(this, initialBuilder)
}
```

```
fun fromData(dataFrame: DataFrame<*>, initialBuilder: DatasetBuilderImpl? = null): NamedDataBuilder {
    return NamedDataBuilder(dataFrame, initialBuilder)
}
```

And its calls from client code

```
val dataBuilder = NamedDataBuilder.fromData(dataFrame, initialBuilder)
```

```
val dataBuilder = dataFrame.fromData(initialBuilder)
```

```
val dataBuilder = fromData(dataFrame, initialBuilder)
```

Honestly, as an extension function it looks weird, top-level function looks better, companion objects for builders not a factory method for constructor replacement looks too Java for me too

2024-06-24 16:05 UTC, zaleslaw commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +            return NamedDataBuilder(dataFrame, initialBuilder)
@devcrocod honestly saying three of them are Kotlin idiomatic, but it should be consistent across the project and serve the readability.

2024-06-24 16:07 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/util.kt
> +        else -> TODO()
TODO? Error? warning? printing the (this)::class?

2024-06-24 16:08 UTC, zaleslaw approved these changes

2024-06-24 16:08 UTC, zaleslaw commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/GroupedDataBuilder.kt
> +            buffer, keys
Looks like Kandy need a linting in a future:))

2024-06-25 12:32 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/util.kt
> +        else -> TODO()
Fixed; in fact I want to remove all TODOs in code but a bit later.

2024-07-09 10:05 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +            return NamedDataBuilder(dataFrame, initialBuilder)
Nope
Using companion object unnecessarily is not Kotlin idiomatic

2024-07-09 10:07 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +            return NamedDataBuilder(dataFrame, initialBuilder)
You can check it if you look at kotlin libs

2024-07-09 10:24 UTC, devcrocod requested changes
There are still comments left unresolved

2024-07-09 10:24 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +        val columnId = addColumn(DataColumn.createValueColumn(name, values, Infer.Type))
What type of column will it be?

2024-07-09 10:24 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +            else -> TODO()
Okay, that doesn't concern us. In this case, you need to throw an exception

2024-07-09 10:24 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +                addColumn(column.rename(column.name() + "*"))
NameGenerator. Okay, it's internal

2024-07-09 10:24 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +        val columnId = addColumn(DataColumn.createValueColumn(name, values, Infer.Type))
I suppose if we have all nulls, than `Infer.Nulls`

2024-07-09 10:26 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/accessors.kt
> +        is MultiLayerPlotBuilder -> datasetBuilder
For me not. And it just helps to navigate the code

2024-07-09 10:38 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/accessors.kt
> +        is MultiLayerPlotBuilder -> datasetBuilder
<img width="823" alt="image" src="https://github.com/Kotlin/kandy/assets/49092338/db202d4c-7af4-4f71-8533-fb797f3b14a7">

2024-07-09 10:39 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/accessors.kt
> +        is MultiLayerPlotBuilder -> datasetBuilder
Do you expect this?
<img width="689" alt="image" src="https://github.com/Kotlin/kandy/assets/49092338/514126d2-c3d6-43fa-9b22-e5e8d324d593">

2024-07-09 10:40 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/accessors.kt
> +        is MultiLayerPlotBuilder -> datasetBuilder
Or what?

2024-07-09 10:49 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +        val columnId = addColumn(DataColumn.createValueColumn(name, values, Infer.Type))
If all values are nulls, then `Nothing?` is inferred and I thinks it's ok.

2024-07-09 10:51 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/accessors.kt
> +        is MultiLayerPlotBuilder -> datasetBuilder
Yes, without cast

2024-07-09 11:01 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +            return NamedDataBuilder(dataFrame, initialBuilder)
@devcrocod please suggest better options

2024-07-09 11:06 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +            return NamedDataBuilder(dataFrame, initialBuilder)
Is `fun DatasetBuilderImpl(): DatasetBuilderImpl ` ok?

2024-07-09 11:18 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +        val columnId = addColumn(DataColumn.createValueColumn(name, values, Infer.Type))
> I suppose if we have all nulls, than Infer.Nulls

2024-07-09 11:20 UTC, AndreiKingsley commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/DatasetBuilderImpl.kt
> +        val columnId = addColumn(DataColumn.createValueColumn(name, values, Infer.Type))
What's a problem?

2024-07-15 19:45 UTC, devcrocod approved these changes

2024-07-15 21:32 UTC, merged