add `plotInset` parameter to style
Kotlin/kandy pull request #431
Opened 2024-09-03 15:38 UTC by lucas-watkins

Try to close #406

2024-09-03 20:39 UTC, AndreiKingsley commented
Looks like `Inset` class is a basically the same as `Margin`. So, may be we don't need another class here, only property/function names.

2024-09-03 20:40 UTC, AndreiKingsley requested changes

2024-09-03 20:40 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/style/CustomStyle.kt
> +public data class Inset(val top: Double, val right: Double, val bottom: Double, val left: Double) {
Just the same as `Margin`

2024-09-03 20:44 UTC, lucas-watkins commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/style/CustomStyle.kt
> +public data class Inset(val top: Double, val right: Double, val bottom: Double, val left: Double) {
Will do, would a typealias be acceptable here?

2024-09-04 07:51 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/style/CustomStyle.kt
> +public data class Inset(val top: Double, val right: Double, val bottom: Double, val left: Double) {
Yes

2024-09-04 09:58 UTC, AndreiKingsley approved these changes

2024-09-04 09:58 UTC, merged