Coordinates API
Kotlin/kandy pull request #447
Opened 2024-11-13 09:40 UTC by AndreiKingsley

Fixes #342.
Adds coordinates API. Removes `coordFlip()`.

2024-11-13 11:48 UTC, zaleslaw commented on kandy-lets-plot/src/test/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/coordinates.kt
> +    @Test
format here!

2024-11-13 11:50 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/coordinates.kt
> +public sealed interface Coordinates : PlotFeature {
Really clear class, appreciate this!

2024-11-13 11:50 UTC, zaleslaw approved these changes

2024-11-21 12:10 UTC, devcrocod requested changes

2024-11-21 12:10 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/feature.kt
> +        (xLimits == null || (xLimits.first == null && xLimits.second == null)) &&
I think this is not the first time I’ve seen pairs check nulls. Maybe it would be worth extracting this into a separate function?

2024-11-21 12:10 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/scaleWrap.kt
This function is very overloaded. It needs to be simplified.

2024-11-21 12:10 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/util.kt
> +        layers.forEach { layer ->
Two forEach calls on layers?

2024-11-21 12:10 UTC, devcrocod commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/util.kt
> +        layers.forEach { layer ->
Combine them
Or use Sequence if a sequence is required.

2024-11-21 12:13 UTC, AndreiKingsley commented on docs/kd.tree
> +        <toc-element topic="Coordinates-API.md"/>
No, it was removed completely.

2024-11-21 12:17 UTC, devcrocod commented on docs/kd.tree
> +        <toc-element topic="Coordinates-API.md"/>
But I saw coordFlip in the wrap function. Is it coordFlip from lets-plot?

2024-11-21 12:27 UTC, AndreiKingsley commented on docs/images/guides/quickStartGuide/basicsGlobalXYBoxplotWithFreeScale.svg
Previous logic for `axis.limits` was incorrect. It changed scale limits, not axis limits. But this's completely different things.

2024-11-21 12:31 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/feature/coordinates.kt
> +        public fun cartesianFlippedFixed(ratio: Double = 1.0): CoordinatesTransformation = CartesianFlippedFixedCoordinatesTransformation(ratio)
1)  It's factory method, that creates instance.
2) name is not overloaded - it's minimal explanation of transformation

2024-11-21 12:31 UTC, AndreiKingsley commented on docs/kd.tree
> +        <toc-element topic="Coordinates-API.md"/>
yes

2024-11-21 12:37 UTC, AndreiKingsley commented on docs/images/guides/quickStartGuide/basicsGlobalXYBoxplotWithFreeScale.svg
You can see it on images comparison: on the old ones, axes are adjusted not properly

2024-11-21 12:42 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/util.kt
> +        layers.forEach { layer ->
Done

2024-11-21 12:42 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/feature.kt
> +        (xLimits == null || (xLimits.first == null && xLimits.second == null)) &&
Done

2024-11-22 12:31 UTC, devcrocod approved these changes

2024-11-25 12:50 UTC, merged