Geo
Kotlin/kandy pull request #449
Opened 2024-11-25 13:00 UTC by AndreiKingsley

2024-12-02 13:41 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/layerWrap.kt
> +            null
If we return null, is it possible to log here something with warning? or throw an exception if we don't handle null higher

2024-12-02 13:41 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/layerWrap.kt
> +    } else null
How should be these null handled?

2024-12-02 13:42 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/data/GeoSpatialData.kt
> +public interface GeoSpatialData: TableData {
Please, generate and fill KDocs

2024-12-02 13:43 UTC, zaleslaw commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/util/mergePolygons.kt
> +
Remove empty line and add some KDocs, great that exception is raised? Could we throw IllegalArgumentException in other situation which I commented?

2024-12-02 13:44 UTC, zaleslaw commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/layers/geoPolygon.kt
> +            error("Not a polygon geometry: $it")
why it somewhere IllegalArgumentException, somewhere error? could it be unified through the PR?

2024-12-02 13:44 UTC, zaleslaw commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/layers/geoPolygon.kt
> +            error("Not a polygon geometry: $it")
Also KDocs required

2024-12-02 13:45 UTC, zaleslaw commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/layers/geoPoints.kt
> +// TODO add ColumnAccessor & String api
TODO: add KDocs

2024-12-02 13:47 UTC, zaleslaw commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/dsl/GeoDataScope.kt
> +public sealed interface GeoDataScope
Is it really required a separate file?

2024-12-02 13:47 UTC, zaleslaw commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/dsl/acсessors.kt
> +@PublishedApi
Sorry, is it @PublishedApi and internal in the same time? Is it correct

2024-12-02 13:48 UTC, zaleslaw commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/dsl/GeoDataFrameScope.kt
> +public class GeoDataFrameScope<T : WithGeometry>(
KDocs please

2024-12-02 13:48 UTC, zaleslaw commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/dsl/GeoDataFramePlotBuilder.kt
> +public class GeoDataFramePlotBuilder<T : WithGeometry> @PublishedApi internal constructor(
KDocs please

2024-12-02 13:49 UTC, zaleslaw commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/dsl/GeoData.kt
> +            val geojson = GeometryJSON(10)
Magic Constant  - should be extracted and explained

2024-12-02 13:49 UTC, zaleslaw commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/dsl/GeoData.kt
> +            return SpatialDataset.withGEOJSON(
is it possible to rename to withGeoJson to be more Kotlinish?

2024-12-02 13:50 UTC, zaleslaw commented on kandy-geo/build.gradle.kts
> +    (this as BaseKotlinCompile).friendPaths.from(jarPaths)
could please add some note or explanation about why do we need friend modules here?

2024-12-02 13:50 UTC, zaleslaw commented on kandy-geo/build.gradle.kts
> +
remove blank lines

2024-12-02 13:51 UTC, zaleslaw requested changes
It requires more work on KDocs and some questions should be answered also

2024-12-02 13:52 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/layerWrap.kt
> +            null
There is no error here, it is a note that in the Lets-Plot specification it is impossible to pass geodataset as main (default for layers), so if we have a main geodatset in kandy, it should be passed to each layer separately during processing and that's exactly what's going here.

2024-12-02 13:54 UTC, AndreiKingsley commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/translator/layerWrap.kt
> +    } else null
It shouldn't, it's a feature of the Lets-Plot specification, which is described in the previous conversation

2024-12-02 13:56 UTC, AndreiKingsley commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/dsl/acсessors.kt
> +@PublishedApi
But `@PublishedApi` is applicable only for internal properties :)

2024-12-02 13:56 UTC, AndreiKingsley commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/dsl/GeoData.kt
> +            return SpatialDataset.withGEOJSON(
It's not our API

2024-12-10 10:20 UTC, AndreiKingsley commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/dsl/GeoDataScope.kt
> +public sealed interface GeoDataScope
why not, plus I added comments to the interface

2024-12-12 15:48 UTC, zaleslaw commented on kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/data/GeoSpatialData.kt
> + * @property dataFrame The data frame containing the geospatial data.
The `DataFrame` (to refer on class), don't use `data frame`

2024-12-12 15:50 UTC, zaleslaw commented on kandy-geo/build.gradle.kts
> +    (this as BaseKotlinCompile).friendPaths.from(jarPaths)
@AndreiKingsley 
add a comment with motivation "what's happened here? and why we did this?"

in this `tasks.withType` snippet

2024-12-12 15:53 UTC, zaleslaw commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/layers/geoLayer.kt
> +        dataFrameOf(geometryColumn).toGeo(null)
I don't understand this code `dataFrameOf(geometryColumn).toGeo(null)`

2024-12-12 15:54 UTC, zaleslaw requested changes
Some moments a little bit unclear, please clarify them

2024-12-12 18:34 UTC, AndreiKingsley commented on kandy-geo/build.gradle.kts
> +    (this as BaseKotlinCompile).friendPaths.from(jarPaths)
I did

2024-12-12 18:35 UTC, AndreiKingsley commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/layers/geoLayer.kt
> +        dataFrameOf(geometryColumn).toGeo(null)
Creating a new dataframe with single column and casting to GeoDataFrame (witn null crs)

2024-12-13 09:35 UTC, devcrocod approved these changes
I left a few comments
Unfortunately, I don't have the opportunity to look more closely later, but overall I approved this

2024-12-13 09:35 UTC, devcrocod commented on kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/dataframe/concatFixed.kt
> +            DataColumn.Companion.createByType(keyName, List(rowsCount) { key[keyName] }, Infer.Type)
Why specify Companion?

2024-12-13 09:35 UTC, devcrocod commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/dsl/GeoData.kt
> +        const val DEFAULT_PRECISION = 10
Is there a way to change this?
Why is it in a companion object and a constant?

2024-12-13 09:35 UTC, devcrocod commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/layers/geoLayer.kt
> +        dataFrameOf(geometryColumn).toGeo(null)
This is not quite in Kotlin style. You can define a copy method with changing parameters

2024-12-13 09:35 UTC, devcrocod commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/layers/geoPolygon.kt
> +        if (it !is Polygonal) {
change to `check`

2024-12-13 09:35 UTC, devcrocod commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/layers/geoRectangles.kt
> +@JvmName("geoRectanglesGeometry")
Why do we need JvmName? Is there a conflict somewhere?

2024-12-13 11:05 UTC, AndreiKingsley commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/dsl/GeoData.kt
> +        const val DEFAULT_PRECISION = 10
it's temporary, will design better way to specify it

2024-12-13 13:14 UTC, AndreiKingsley commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/layers/geoLayer.kt
> +        dataFrameOf(geometryColumn).toGeo(null)
What do you mean?

2024-12-13 13:19 UTC, AndreiKingsley commented on kandy-geo/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/geo/layers/geoRectangles.kt
> +@JvmName("geoRectanglesGeometry")
Yes:
```
Platform declaration clash: The following declarations have the same JVM signature (geoRectangles(Lorg/jetbrains/kotlinx/kandy/dsl/internal/LayerCreatorScope;Ljava/lang/Iterable;Lkotlin/jvm/functions/Function1;)V):
    fun LayerCreatorScope.geoRectangles(geometry: Iterable<Envelope>, block: (RectanglesBuilder) -> Unit = ...): Unit defined in org.jetbrains.kotlinx.kandy.letsplot.geo.layers
    fun LayerCreatorScope.geoRectangles(geometry: Iterable<Geometry>, block: (RectanglesBuilder) -> Unit = ...): Unit defined in org.jetbrains.kotlinx.kandy.letsplot.geo.layers

2024-12-13 13:28 UTC, merged